// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgq9vdlKeHjykMhK1nDKwiEsg99NpKerc',
    appId: '1:360230907282:web:b29e957c3996f84456254b',
    messagingSenderId: '360230907282',
    projectId: 'famlist-app',
    authDomain: 'famlist-app.firebaseapp.com',
    storageBucket: 'famlist-app.appspot.com',
    measurementId: 'G-TLRVM35X6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQD6msVcNw56lTocmCYOLjeiPj-dmPJw',
    appId: '1:360230907282:android:f2b718547724a7fd56254b',
    messagingSenderId: '360230907282',
    projectId: 'famlist-app',
    storageBucket: 'famlist-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUevYy_34YZbWrOjaX_MP8KWux_wKw7aY',
    appId: '1:360230907282:ios:ec3ad971d24f40ec56254b',
    messagingSenderId: '360230907282',
    projectId: 'famlist-app',
    storageBucket: 'famlist-app.appspot.com',
    iosClientId: '360230907282-ck85r4k02krf34bbkrpullftem1j0l97.apps.googleusercontent.com',
    iosBundleId: 'com.logicgear.famlist',
  );
}
