const String defaultListTitle = "Tu lista de la compra";
const String appStartError = "Algo salió mal. Por favor, intentalo mas tarde";
const String addList = "Añadir lista";
const String addProduct = "Añadir producto";
const String name = "Nombre";
const String listName = "Nombre de la lista";
const String create = "Añadir";
const String appName = "Famlist";
const String yourLists = "Tus listas";